# Generated by Django 3.0.1 on 2020-10-31 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity_unit', models.CharField(choices=[('g', 'gram'), ('ltr', 'liter'), ('kg', 'kilogram'), ('pc', 'pieces'), ('tbsp', 'table spoon'), ('tsp', 'tea spoon')], default='kg', max_length=200)),
                ('unit_cost_prices', models.FloatField(default=0, verbose_name='Cost Price per unit')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='category ', max_length=200)),
                ('unit', models.CharField(choices=[('lb', 'pound'), ('gm', 'grams'), ('kg', 'kilogram'), ('pcs', 'piece')], default='kg', max_length=200)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter name', max_length=200)),
                ('profit', models.FloatField(default=0, help_text='this is calculated in percentage ')),
                ('cost_price', models.FloatField(default=0, help_text='this is calculated using ingredint cost with its quantity')),
                ('selling_price', models.FloatField(default=0, help_text='calculated on basis of profit')),
                ('descriptions', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(default='Category of this product item', on_delete=django.db.models.deletion.CASCADE, to='management_app.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='quanity of ingredient in Dish ')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Dishes')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Ingredients')),
            ],
        ),
    ]
